[build]
command = "pelican"
publish = "output"

[[headers]]
for = "/*"

[headers.values]
  Content-Security-Policy = "default-src 'none'; style-src 'self'"
          Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=15768000"
   X-Content-Type-Options = "nosniff"
          X-Frame-Options = "DENY"
         X-XSS-Protection = "1; mode=block"
