ARCHIVES_SAVE_AS = ""
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None
AUTHORS_SAVE_AS = ""
CATEGORIES_SAVE_AS = ""
CATEGORY_FEED_ATOM = None
DEFAULT_LANG = "en"
DELETE_OUTPUT_DIRECTORY = True
EXTRA_PATH_METADATA = {"images/gitignore.txt": {"path": ".gitignore"}}
FEED_ALL_ATOM = None
LOAD_CONTENT_CACHE = True
PAGE_SAVE_AS = "recipes/{slug}.html"
PAGE_URL = "recipes/{slug}"
PATH = "content"
# RELATIVE_URLS = True
SITENAME = "Jackson Family Recipes"
# SITEURL = ''
TAGS_SAVE_AS = ""
THEME = "themes/default"
TIMEZONE = "America/Chicago"
TRANSLATION_FEED_ATOM = None
